/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQL;

/**
 *
 * @author exequ
 */

import java.awt.Color;
import java.sql.*;
import javax.sound.midi.SoundbankResource;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Mostrar() {
        initComponents();
  
        rsscalelabel.RSScaleLabel.setScaleLabel(jlHome, "src/images/home.png");
        jpHomeSelect.setVisible(false);
      
    }
    
    //Metodo para mostrar datos en la tabla

    /*
    private void Mostrar(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object []{"nombre", "contraseña"});
        try{
            Statement statement = ConexionSQL.getConexion().createStatement();
            String query = "SELECT * FROM tbUsuarios";
            ResultSet rs = statement.executeQuery(query);
            
            while(rs.next()){
                modelo.addRow(new Object[] {rs.getString("nombre"),rs.getString("contraseña")});
            }
            JT_personas.setModel(modelo);
            
        }catch(SQLException ex){
            System.out.println(ex.toString());
        }
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_personas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jlHome = new javax.swing.JLabel();
        jpHomeSelect = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JT_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_personasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JT_personas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 150));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlHome.setBackground(new java.awt.Color(255, 255, 255));
        jlHome.setForeground(new java.awt.Color(255, 255, 255));
        jlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlHomeMouseExited(evt);
            }
        });
        jPanel2.add(jlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 40));

        jpHomeSelect.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHomeSelectLayout = new javax.swing.GroupLayout(jpHomeSelect);
        jpHomeSelect.setLayout(jpHomeSelectLayout);
        jpHomeSelectLayout.setHorizontalGroup(
            jpHomeSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jpHomeSelectLayout.setVerticalGroup(
            jpHomeSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jpHomeSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 80, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHomeMouseExited
       jpHomeSelect.setVisible(false);
    }//GEN-LAST:event_jlHomeMouseExited

    private void jlHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHomeMouseEntered
       jpHomeSelect.setVisible(true);
    }//GEN-LAST:event_jlHomeMouseEntered

    private void jlHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHomeMouseClicked
        jpHomeSelect.setVisible(true);
    }//GEN-LAST:event_jlHomeMouseClicked

    private void JT_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_personasMouseClicked
     
    }//GEN-LAST:event_JT_personasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JT_personas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlHome;
    private javax.swing.JPanel jpHomeSelect;
    // End of variables declaration//GEN-END:variables
}
